### ISSUE TITLE
Component not found

### ISSUE THREAD

**Issue by ipelekhan** [TravnikovRN/binance-cryptocurrency-widget#2]
Hi, seems like the component is not published to the NPM registry. How can I install it?

![image](https://user-images.githubusercontent.com/2616427/85392727-4059f280-b54c-11ea-8564-cb35682c2e35.png)

**Comment by TravnikovRN** [comment]
> Hi, seems like the component is not published to the NPM registry. How can I install it?
Publish package to NPM https://www.npmjs.com/package/binance-cryptocurrency-widget
Enjoy
